### ISSUE TITLE
import pomegranate error

### ISSUE THREAD

**Issue by asincerity** [jmschrei/pomegranate#1093]
My pomegranate==0.12.2 scipy ==1.4.1 
When I import pomegranate，it report the error：
Traceback (most recent call last):
  File "E:/programme/DeepFRET-Model/test.py", line 1, in <module>
    import pomegranate
  File "E:\programme\DeepFRET-Model\venv\lib\site-packages\pomegranate\__init__.py", line 11, in <module>
    from .base import *
  File "pomegranate\base.pyx", line 6, in init pomegranate.base
  File "E:\programme\DeepFRET-Model\venv\lib\site-packages\pomegranate\distributions\__init__.py", line 9, in <module>
    from .distributions import *
  File "pomegranate\distributions\distributions.pyx", line 12, in init pomegranate.distributions.distributions
  File "pomegranate\utils.pyx", line 1, in init pomegranate.utils
  File "E:\programme\DeepFRET-Model\venv\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "E:\programme\DeepFRET-Model\venv\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "E:\programme\DeepFRET-Model\venv\lib\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: 找不到指定的模块。

Thanks for your attention。

**Comment by jmschrei** [comment]
Howdy

Sorry you're encountering an issue. This looks like an import issue with scipy, not with pomegranate. I know that sometimes scipy has these difficult-to-understand import issues. I'm not sure what the issue is -- maybe try reinstalling scipy?
