### ISSUE TITLE
Error in GMM

### ISSUE THREAD

**Issue by jmgo** [jmschrei/pomegranate#125]
Hi!

I was trying to use GMM and I used the following code from your tutorial:  

```
import numpy as np

data = np.concatenate( (np.random.randn(250) * 2.75 + 1.25, np.random.randn(500) * 1.2 + 7.85) )
np.random.shuffle(data)

d = GeneralMixtureModel( [NormalDistribution(2.5, 1), NormalDistribution(8, 1)] )
d.fit( data, verbose=True )
```

I ran this code but got the following error:

```
Traceback (most recent call last):
  File "test_pomegranate_gmm.py", line 10, in <module>
    d.fit( data, verbose=True )
  File "pomegranate/gmm.pyx", line 687, in pomegranate.gmm.GeneralMixtureModel.fit (pomegranate/gmm.c:8068)
TypeError: object of type 'numpy.float64' has no len()
```

I even tried converting data to list (thinking that the input might be a list), but got another error:

```
Traceback (most recent call last):
  File "test_pomegranate_gmm.py", line 10, in <module>
    d.fit( data.tolist(), verbose=True )
  File "pomegranate/gmm.pyx", line 687, in pomegranate.gmm.GeneralMixtureModel.fit (pomegranate/gmm.c:8068)
TypeError: object of type 'float' has no len()
```

Am I missing something or is just a bug?

Regards, 
jmgo

**Comment by jmschrei** [comment]
Hi jmgo

The input has to be a 2 dimensional matrix, even for 1d data. This assumption makes it a lot easier for us internally.

Just do the following:

```
data = np.concatenate( (np.random.randn(250, 1) * 2.75 + 1.25, np.random.randn(500, 1) * 1.2 + 7.85) )
```

**Comment by jmschrei** [comment]
Alternatively reshape it at the end like so:

```
data = data.reshape( data.shape[0], 1 )
```

**Comment by jmgo** [comment]
Ok, thanks for the reply!

Regards, 
jmgo

**Comment by jmgo** [comment]
Hi!

Sorry for bothering again. 

I was trying to use the MixtureDistribution by using the following code:

```
d = MixtureDistribution([NormalDistribution(2, 4), ExponentialDistribution(8)], weights=[1, 0.01])

data = np.array( [1, 5, 7, 3, 2, 4, 3, 5, 7, 8, 2, 4, 6, 7, 2, 4, 5, 1, 3, 2, 1] ) 
data = data.reshape( data.shape[0], 1 )

d.fit(data)
```

and got the following error:

```
Traceback (most recent call last):
  File "test_pomegranate_gmm.py", line 19, in <module>
    d.fit(data)
  File "pomegranate/distributions.pyx", line 249, in pomegranate.distributions.Distribution.fit (pomegranate/distributions.c:4957)
NotImplementedError
```

Does this mean that the MixtureDistribution is not yet implemented?

Regards,
jmgo

**Comment by jmschrei** [comment]
Use GeneralMixtureModel

**Comment by jmschrei** [comment]
Did this end up working for you?
