### ISSUE TITLE
JSON export: SyntaxError: Distribution object attempting to read invalid object.

### ISSUE THREAD

**Issue by pixelou** [jmschrei/pomegranate#148]
Hello,

I hope I am not using pomegranate in a wrong way, but I think the JSON exportation is not working properly for GMM-HMM:

The minimal working example is :
```python
from pomegranate.hmm import HiddenMarkovModel

with open("model.json.txt") as f:
    HiddenMarkovModel.from_json(f.read())
    print("ok")

# The following code works fine so the JSON structure must be valid:
# import json
#
# with open("model.json.txt") as f:
#     o = json.loads(f.read())
#     print(o)
```

And yields:

```
python minimal.py
Traceback (most recent call last):
  File "minimal.py", line 4, in <module>
    HiddenMarkovModel.from_json(f.read())
  File "pomegranate/hmm.pyx", line 2979, in pomegranate.hmm.HiddenMarkovModel.from_json (pomegranate/hmm.c:33504)
  File "pomegranate/base.pyx", line 132, in pomegranate.base.State.from_json (pomegranate/base.c:4224)
  File "pomegranate/distributions.pyx", line 404, in pomegranate.distributions.Distribution.from_json (pomegranate/distributions.c:6269)
SyntaxError: Distribution object attempting to read invalid object.
```

for this model : [model.json.txt](https://github.com/jmschrei/pomegranate/files/345970/model.json.txt)

The model was generated using the following procedure:

```python
def train_gmm_hmm(n_states, n_components, observations, name="hmm"):
    # Build model
    dists = [GeneralMixtureModel(
                [MultivariateGaussianDistribution(
                    means=np.zeros((7,)), covariance=np.diag(np.ones((7,))))
                    for _ in range(n_components)])
             for _ in range(n_states)]
    states = [State(dist, name="S"+str(i)) for i, dist in enumerate(dists)]
    model = HiddenMarkovModel(name)
    model.add_states(states)
    model.add_transition(model.start, states[0], 1)
    for i in range(len(states) - 1):
        model.add_transition(states[i], states[i], .8)
        model.add_transition(states[i], states[i+1], .2)
    model.add_transition(states[-1], states[-1], .9)
    model.add_transition(states[-1], model.end, .1)
    model.bake()

    # Fit model
    model.fit(observations, stop_threshold=1e-3, max_iterations=100, verbose=True)

    return model.to_json()  # or .copy() which relies on .to_json()
```

As far as I can tell, the training procedure seems to run properly.

Regards,

**Comment by jmschrei** [comment]
I was able to track down the bug. Please clone the latest copy of the code and let me know if it works for you!

**Comment by pixelou** [comment]
Yep, it's ok now.
And thank you very much for this awesome library. :-)

**Comment by jmschrei** [comment]
Let me know if you encounter any other issues!
