### ISSUE TITLE
Pip installation issues ValueError: 'pomegranate/*.pyx' doesn't match any files

### ISSUE THREAD

**Issue by dmmiller612** [jmschrei/pomegranate#333]
Hello everyone,

First I wanted to say that this repo looks really well done, and I am excited about using the probabilistic models. I know that the maintainers are probably pretty busy, so I am willing to help out where it makes sense with this issue. On my mac OSX, I ran into an issue where I can't pip install pomegranate. When running both `pip install pomegranate` and `pip install pomegranate --no-cache-dir`, I get the following error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jp/sh4l4l4x4vb216bqy49y87v00000gn/T/pip-build-DG1HK3/pomegranate/setup.py", line 34, in <module>
        extensions = cythonize( extensions )
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 908, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 778, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 124, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jp/sh4l4l4x4vb216bqy49y87v00000gn/T/pip-build-DG1HK3/pomegranate/
```

I looked at the readme, and it mentioned demoting a couple of libraries, but that didn't seem to do the trick. Do you have any other thoughts?

EDIT:

here is my pip list in my virtual environment:

```
Cython (0.27.1)
decorator (4.1.2)
joblib (0.11)
networkx (1.11)
numpy (1.11.3)
pip (9.0.1)
scipy (0.19.1)
setuptools (36.6.0)
wheel (0.30.0)
```

**Comment by mohataher** [comment]
```
pip install git+https://github.com/jmschrei/pomegranate.git
```

After installing dependencies, this line will solve your problems. I have tested that command on OSX on both `pip3` and `pip`.

I have updated the README file and submitted a pull request.

**Comment by jmschrei** [comment]
@dmmiller612 let me know if that suggestion solves your problems. Thanks @mohataher!

**Comment by dmmiller612** [comment]
looking now.

**Comment by dmmiller612** [comment]
Thanks a ton @mohataher ! This solved my problem

**Comment by jmschrei** [comment]
Great, thanks!

**Comment by B4marc** [comment]
Hi @-all, 
unfortunately I am facing the same problem with win 10 64x. 
I am using the IDE PyCharm and Visual Studio 2017. My libs versions are: 

- Cython (0.27.1)
- decorator (4.1.2)
- joblib (0.11)
- networkx (1.11)
- numpy (1.14.3)
- pip (100.1)
- scipy (1.1.0)
- setuptools (39.0.1)
- wheel (0.30.0)

But trying to update, this error message occures:

> Collecting pomegranate==0.9.0
  Using cached https://files.pythonhosted.org/packages/1c/68/c4ef8a696656f08515b1a9c224136962a9c7485b755fd5d1ea51d3699f4e/pomegranate-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lamarck\AppData\Local\Temp\pycharm-packaging\pomegranate\setup.py", line 34, in <module>
        extensions = cythonize( extensions )
      File "C:\Users\Lamarck\Documents\Coding\Python\PA\venv\lib\site-packages\Cython\Build\Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "C:\Users\Lamarck\Documents\Coding\Python\PA\venv\lib\site-packages\Cython\Build\Dependencies.py", line 800, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "C:\Users\Lamarck\Documents\Coding\Python\PA\venv\lib\site-packages\Cython\Build\Dependencies.py", line 125, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lamarck\AppData\Local\Temp\pycharm-packaging\pomegranate\    
    ----------------------------------------

However, Pomergranate 0.8 is working.
Has anyone have a solution?
Thank you in advance!

**Comment by jkleckner** [comment]
@dmmiller612 I wonder if #406 might fix that problem?

**Comment by dmmiller612** [comment]
I was able to solve the problem using the solution above while ago.

**Comment by jaideepmurkute** [comment]
Thanks @mohataher ...your solution totally worked for me! and thanks @jmschrei for the amazing work with the library.

**Comment by B4marc** [comment]
Hi, 
first of all, thanks for your hints! It worked out. I am actually not that familiar with environments und the cmd, but this [link](https://stackoverflow.com/questions/11000869/command-line-git-on-windows) helped me to use the solution of mohataher. @mohataher thanks!

**Comment by WTRipper** [comment]
I am getting the same error and installing from git does not work as well.
My Setup:
```
Windows 10 Home 64bit
Python 3.6.2
Build Tools for Visual Studio 2017 from https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15
```

Installed Packages in my virtual environment:
```
Cython==0.28.5
decorator==4.3.0
joblib==0.12.3
networkx==1.11
numpy==1.15.1
PyYAML==3.13
scipy==1.1.0
```
When I use `pip install pomegranate` or `pip install pomegranate --no-cache-dir` I am getting :

```
Collecting pomegranate
  Downloading https://files.pythonhosted.org/packages/b0/53/c8916c804f684291a907b4171e998efcf75ee851f722751f0b999b450866/pomegranate-0.10.0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB ...
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-install-l1mk_nd1\pomegranate\setup.py", line 60, in <module>
        extensions = cythonize( extensions )
      File "c:\users\...\venv\lib\site-packages\Cython\Build\Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "c:\users\...\venv\lib\site-packages\Cython\Build\Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "c:\users\...\venv\lib\site-packages\Cython\Build\Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-install-l1mk_nd1\pomegranate\
```
When I use `pip.exe install git+https://github.com/jmschrei/pomegra
nate.git`:
```
Collecting git+https://github.com/jmschrei/pomegranate.git
  Cloning https://github.com/jmschrei/pomegranate.git to c:\users\...\appdata\local\temp\pip-req-build-gm1v0azq
Requirement already satisfied: numpy>=1.8.0 in c:\users\...\venv\lib\site-packages (from pomegranate==0.10.0) (1.15.1)
Requirement already satisfied: joblib>=0.9.0b4 in c:\users\...\venv\lib\site-packages (from pomegranate==0.10.0) (0.12.3)
Requirement already satisfied: networkx<2.0,>=1.8.1 in c:\users\...\venv\lib\site-packages (from pomegranate==0.10.0) (1.11)
Requirement already satisfied: scipy>=0.17.0 in c:\users\...\venv\lib\site-packages (from pomegranate==0.10.0) (1.1.0)
Requirement already satisfied: pyyaml in c:\users\...\venv\lib\site-packages (from pomegranate==0.10.0) (3.13)
Requirement already satisfied: decorator>=3.4.0 in c:\users\...\venv\lib\site-packages (from networkx<2.0,>=1.8.1->pomegranate==0.10.0) (4.3.0)
Building wheels for collected packages: pomegranate
  Running setup.py bdist_wheel for pomegranate ... error
  Complete output from command c:\users\....\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\...\\AppData\\Local\\Temp\\pip-req-build-gm1v0azq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\...\AppData\Local\Temp\pip-wheel-xlp1eooq --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\callbacks.py -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\__init__.py -> build\lib.win-amd64-3.6\pomegranate
  creating build\lib.win-amd64-3.6\pomegranate\distributions
  copying pomegranate/distributions\__init__.py -> build\lib.win-amd64-3.6\pomegranate/distributions
  running egg_info
  creating pomegranate.egg-info
  writing pomegranate.egg-info\PKG-INFO
  writing dependency_links to pomegranate.egg-info\dependency_links.txt
  writing requirements to pomegranate.egg-info\requires.txt
  writing top-level names to pomegranate.egg-info\top_level.txt
  writing manifest file 'pomegranate.egg-info\SOURCES.txt'
  reading manifest file 'pomegranate.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pomegranate.egg-info\SOURCES.txt'
  copying pomegranate\BayesClassifier.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\BayesianNetwork.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\FactorGraph.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\MarkovChain.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\NaiveBayes.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\base.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\base.pxd -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\bayes.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\bayes.pxd -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\gmm.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\hmm.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\kmeans.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\parallel.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\utils.c -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate\utils.pxd -> build\lib.win-amd64-3.6\pomegranate
  copying pomegranate/distributions\BernoulliDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\BetaDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\ConditionalProbabilityTable.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\DirichletDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\DiscreteDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\ExponentialDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\GammaDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\IndependentComponentsDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\JointProbabilityTable.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\KernelDensities.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\LogNormalDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\MultivariateGaussianDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\NormalDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\PoissonDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\UniformDistribution.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\distributions.c -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\BernoulliDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\BetaDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\ConditionalProbabilityTable.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\DirichletDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\DiscreteDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\distributions.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\ExponentialDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\GammaDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\IndependentComponentsDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\JointProbabilityTable.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\KernelDensities.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\LogNormalDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\MultivariateGaussianDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\NormalDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\PoissonDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  copying pomegranate/distributions\UniformDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
  running build_ext
  building 'pomegranate.BayesClassifier' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\pomegranate
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\users\...\venv\include -ID:\Python36\include -ID:\Python36\include -Ic:\users\...\venv\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcpomegranate\BayesClassifier.c /Fobuild\temp.win-amd64-3.6\Release\pomegranate\BayesClassifier.obj
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pomegranate
  Running setup.py clean for pomegranate
Failed to build pomegranate
Installing collected packages: pomegranate
  Running setup.py install for pomegranate ... error
    Complete output from command c:\users\...\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\...\\AppData\\Local\\Temp\\pip-req-build-gm1v0azq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\...\AppData\Local\Temp\pip-record-jf5b1_vz\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\...\venv\include\site\python3.6\pomegranate:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\callbacks.py -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\__init__.py -> build\lib.win-amd64-3.6\pomegranate
    creating build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate/distributions\__init__.py -> build\lib.win-amd64-3.6\pomegranate/distributions
    running egg_info
    writing pomegranate.egg-info\PKG-INFO
    writing dependency_links to pomegranate.egg-info\dependency_links.txt
    writing requirements to pomegranate.egg-info\requires.txt
    writing top-level names to pomegranate.egg-info\top_level.txt
    reading manifest file 'pomegranate.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pomegranate.egg-info\SOURCES.txt'
    copying pomegranate\BayesClassifier.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\BayesianNetwork.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\FactorGraph.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\MarkovChain.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\NaiveBayes.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\base.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\base.pxd -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\bayes.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\bayes.pxd -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\gmm.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\hmm.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\kmeans.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\parallel.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\utils.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\utils.pxd -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\distributions\BernoulliDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\BetaDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\ConditionalProbabilityTable.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\DirichletDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\DiscreteDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\ExponentialDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\GammaDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\IndependentComponentsDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\JointProbabilityTable.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\KernelDensities.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\LogNormalDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\MultivariateGaussianDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\NormalDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\PoissonDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\UniformDistribution.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate\distributions\distributions.c -> build\lib.win-amd64-3.6\pomegranate\distributions
    copying pomegranate/distributions\BernoulliDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\BetaDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\ConditionalProbabilityTable.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\DirichletDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\DiscreteDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\distributions.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\ExponentialDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\GammaDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\IndependentComponentsDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\JointProbabilityTable.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\KernelDensities.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\LogNormalDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\MultivariateGaussianDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\NormalDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\PoissonDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    copying pomegranate/distributions\UniformDistribution.pxd -> build\lib.win-amd64-3.6\pomegranate/distributions
    running build_ext
    building 'pomegranate.BayesClassifier' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pomegranate
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\users\...\venv\include -ID:\Python36\include -ID:\Python36\include -Ic:\users\...\venv\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcpomegranate\BayesClassifier.c /Fobuild\temp.win-amd64-3.6\Release\pomegranate\BayesClassifier.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\users\...\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\...\\AppData\\Local\\Temp\\pip-req-build-gm1v0azq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\...\AppData\Local\Temp\pip-record-jf5b1_vz\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\...\venv\include\site\python3.6\pomegranate" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-req-build-gm1v0azq\
```

**Comment by WTRipper** [comment]
By following the instructions from [here](https://pomegranate.readthedocs.io/en/latest/install.html) and [here](https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158) it seems to work now:

1. Installing building tools from [here](http://go.microsoft.com/fwlink/?LinkId=691126)
2. `git clone https://github.com/jmschrei/pomegranate`
3. `cd pomegranate`
4. Copy `rc.exe` `rcdll.dll` from `C:\Program Files (x86)\Windows Kits\8.1\bin\x86` to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin`
5. `python setup.py install`

**Comment by fastluca** [comment]
Hi all, someone solved this issue?
If yes, which is the process to install the library on w10?

**Comment by alimanfoo** [comment]
Just hit this problem, trying to install pomegranate on windows ([appveyor](https://ci.appveyor.com/project/alimanfoo/scikit-allel/builds/21160075/job/0fyxfh12f1iobws3)). Checking the [source distribution for 0.10.0](https://files.pythonhosted.org/packages/b0/53/c8916c804f684291a907b4171e998efcf75ee851f722751f0b999b450866/pomegranate-0.10.0.tar.gz), the .pyx files are not included, only the .c files. Looking at [MANIFEST.in](https://github.com/jmschrei/pomegranate/blob/master/MANIFEST.in), the .pyx files are not included there, only .pxd and .c, which is probably why the .pyx files are not ending up in the source distribution.

So if someone tries to install pomegranate on windows but doesn't have cython installed, it will probably work (build from .c), but if cython is present then it won't work (attempt to build from .pyx but .pyx are missing from source distribution).

This doesn't crop up on Linux because by default a prebuilt wheel gets installed. If you to ``pip install --no-binary`` then you get the problem reported here.

Surely the right thing to do here is add:

```
include pomegranate/*.pyx
```

...to MANIFEST.in and issue a new source release.

Happy to submit a PR to that effect.

**Comment by kevinlib** [comment]
having this same issue trying build pomegranate v0.8.1 on mac
