### ISSUE TITLE
.pyx files missing from sdist on PyPI

### ISSUE THREAD

**Issue by nehaljwani** [jmschrei/pomegranate#341]
The sdist uploaded on PyPI doesn't have the .pyx files, so one cannot use that with Cython to build the package. Please also add the .pyx files in the Manifest

**Comment by Divye02** [comment]
if you are on a MAC, I tried installing the 0.7.0 version instead of 0.8.0 and it worked

**Comment by nehaljwani** [comment]
@Divye02 You can use conda to get the latest version. `conda install -c anaconda pomegranate`

**Comment by jmschrei** [comment]
Are you saying that pip works to download the package, but if you'd like to build from source you can't? I'll try to put the .pyx files in the next release, but if you want to build from source you should clone the GitHub repo.

**Comment by nehaljwani** [comment]
@jmschrei Yes, that's exactly what I meant.

**Comment by nehaljwani** [comment]
This is what happens at the moment:
```
(test7) [root@8a840e4386e3 ~]# pip freeze
certifi==2017.7.27.1
Cython==0.26.1
numpy==1.13.3
(test7) [root@8a840e4386e3 ~]# pip install pomegranate
Collecting pomegranate
  Using cached pomegranate-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d0gqpprm/pomegranate/setup.py", line 34, in <module>
        extensions = cythonize( extensions )
      File "/opt/conda/envs/test7/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 908, in cythonize
        aliases=aliases)
      File "/opt/conda/envs/test7/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 778, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/opt/conda/envs/test7/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 124, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d0gqpprm/pomegranate/
```

**Comment by jmschrei** [comment]
This should be fixed with the creation of Mac and Linux wheels. Re-open if you encounter this issue again.
