### ISSUE TITLE
Leading minor is not positve define in Multivariate HMM

### ISSUE THREAD

**Issue by rzu512** [jmschrei/pomegranate#478]
I get this error from the pomegranate package from anaconda and the current master branch here.

When I use my real data, I get a similar error message for the `2917-th leading minor`

Test:
```python
import pomegranate as pg
import numpy as np

n = 4
d = 1000
x = np.random.randint(2, size=(n, d), dtype=bool)
x[3] = x[1] & x[2]
X = [x]

model = pg.HiddenMarkovModel.from_samples(
    pg.MultivariateGaussianDistribution,
    n_components=2, X=X,
    verbose=True)
```

Error:
```
Traceback (most recent call last):
  File "pomegranate/distributions.pyx", line 2254, in pomegranate.distributions.MultivariateGaussianDistribution.from_summaries
  File "<...python3.6>/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "<...python3.6>/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.linalg.LinAlgError: 2-th leading minor of the array is not positive definite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<...>hmm.py", line 13, in <module>
    verbose=True)
  File "pomegranate/hmm.pyx", line 3594, in pomegranate.hmm.HiddenMarkovModel.from_samples
  File "pomegranate/distributions.pyx", line 2284, in pomegranate.distributions.MultivariateGaussianDistribution.from_samples
  File "pomegranate/distributions.pyx", line 205, in pomegranate.distributions.Distribution.fit
  File "pomegranate/distributions.pyx", line 2259, in pomegranate.distributions.MultivariateGaussianDistribution.from_summaries
TypeError: Cannot cast ufunc subtract output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```

Same error when the variables are all independent:
```
import pomegranate as pg
import numpy as np

n = 4
d = 1000
dtype = bool
x = np.random.randint(4, size=(n, d), dtype=dtype)
X = [x]

model = pg.HiddenMarkovModel.from_samples(
    pg.MultivariateGaussianDistribution,
    n_components=2, X=X,
    verbose=True)
```

**Comment by jmschrei** [comment]
Try updating to v0.10.0 and let me know if this is still an issue.

**Comment by jmschrei** [comment]
Please re-open if this is still an issue.

**Comment by scottgigante** [comment]
I'm having the same problem. I have version 0.10.0 and the exact code above throws the same errors as described.
