### ISSUE TITLE
Error when using n_jobs in predict()

### ISSUE THREAD

**Issue by relue** [jmschrei/pomegranate#570]
I have 5 CPU cores available. If I use predict() with n_jobs > 3 I get the error below. But if I use the predict_proba() it works up to 5. Do I miss something?

pydev debugger: process 11746 is connecting
Traceback (most recent call last):
  File "/snap/pycharm-community/117/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 141, in patch_args
    host, port = _get_host_port()
  File "/snap/pycharm-community/117/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 43, in _get_host_port
    host, port = pydevd.dispatch()
  File "/snap/pycharm-community/117/helpers/pydev/pydevd.py", line 1487, in dispatch
    host = setup['client']
TypeError: 'NoneType' object is not subscriptable
pydev debugger: process 11759 is connecting

**Comment by relue** [comment]
It seems debugging mode causes this as I have this problem not without.
