### ISSUE TITLE
Create custom power law distribution

### ISSUE THREAD

**Issue by titipata** [jmschrei/pomegranate#574]
Hi here, I'm wondering if there is a plan to add an implementation of power-law distribution e.g. `f(x) = C (x ** -alpha)` in the repository. I saw the [custom distribution notebook](https://github.com/jmschrei/pomegranate/blob/76cbc0cb242911905429e8629d8bed02b85d77d6/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb) but still could not implement my own. If there is any suggestion on the implementation, that would be great!

**Comment by titipata** [comment]
I have tried the following

```python
import scipy.stats

class PowerLawDistribution():
    def __init__(self, a):
        self.a = a
        self.parameters = (self.a)
        self.d = 1
        self.summaries = numpy.zeros(3)
        self.frozen = False
        self.name = 'PowerLawDistribution'

    def probability(self, X):
        return numpy.exp(self.log_probability(X))
        
    def log_probability(self, X):
        return scipy.stats.powerlaw.logpdf(X, self.a)

    def summarize(self, X, w=None):
        if w is None:
            w = numpy.ones(X.shape[0])

        X = X.reshape(X.shape[0])
        self.summaries[0] += w.sum()
        self.summaries[1] += X.dot(w)
        self.summaries[2] += (X ** 2.).dot(w)

    def from_summaries(self, inertia=0.0):
        self.mu = self.summaries[1] / self.summaries[0]
        self.std = self.summaries[2] / self.summaries[0] - self.summaries[1] ** 2 / (self.summaries[0] ** 2)
        self.std = numpy.sqrt(self.std)
        self.parameters = (self.mu, self.std)
        self.clear_summaries()

    def clear_summaries(self, inertia=0.0):
        self.summaries = numpy.zeros(3)

    @classmethod
    def from_samples(cls, X, weights=None, df=1):
        d = PowerLawDistribution(0)
        d.summarize(X, weights)
        d.from_summaries()
        return d

    @classmethod
    def blank(cls):
        return PowerLawDistribution(0)
    
    @classmethod
    def to_json(self, separators=(',', ' : '), indent=4):
        """Convert the distribution to JSON format."""
        return json.dumps(
            {
                'class' : 'Distribution',
                'name'  : self.name,
                'parameters' : [[json.loads(dist.to_json()) for dist in self.parameters[0]],
                                self.parameters[1]],
                'frozen' : self.frozen
            },
            separators=separators, indent=indent
        )
```

However, when I tried to fit the data, I got the following errors:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    396                             if callable(meth):
    397                                 return meth(obj, self, cycle)
--> 398             return _default_pprint(obj, self, cycle)
    399         finally:
    400             self.end_group()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    516     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    517         # A user-provided repr. Find newlines and replace them with p.break_()
--> 518         _repr_pprint(obj, p, cycle)
    519         return
    520     p.begin_group(1, '<')

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

pomegranate/base.pyx in pomegranate.base.Model.__repr__()

pomegranate/gmm.pyx in pomegranate.gmm.GeneralMixtureModel.to_json()

<ipython-input-162-92ff4b6eaf1f> in to_json(self, separators, indent)
     52             {
     53                 'class' : 'Distribution',
---> 54                 'name'  : self.name,
     55                 'parameters' : [[json.loads(dist.to_json()) for dist in self.parameters[0]],
     56                                 self.parameters[1]],

AttributeError: type object 'PowerLawDistribution' has no attribute 'name'
```

**Comment by jmschrei** [comment]
`to_json` shouldn't be a class method. Can you try removing that decorator
and fitting again?

**Comment by titipata** [comment]
Yes, so I got the following error instead

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    396                             if callable(meth):
    397                                 return meth(obj, self, cycle)
--> 398             return _default_pprint(obj, self, cycle)
    399         finally:
    400             self.end_group()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    516     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    517         # A user-provided repr. Find newlines and replace them with p.break_()
--> 518         _repr_pprint(obj, p, cycle)
    519         return
    520     p.begin_group(1, '<')

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

pomegranate/base.pyx in pomegranate.base.Model.__repr__()

pomegranate/gmm.pyx in pomegranate.gmm.GeneralMixtureModel.to_json()

AttributeError: 'PowerLawDistribution' object has no attribute 'to_json'
```

I'm not sure if I'm following the right notebook to create the new distribution.

**Comment by jmschrei** [comment]
I'm guessing that you're trying to fit a mixture of power law distributions, and that you're doing this in a Jupyter notebook where the line is `model.fit(...data...)`. The notebook is trying to return the string distribution of the model, and there's some issue with serialization. You can circumvent this entirely by doing something like `_ = model.fit(...data...)`, so that the notebook cell doesn't get prompted to return anything. 

I'll be able to offer more advice if I could see what code you're running. Can you provide either the code, or a screen shot of the notebook?

**Comment by titipata** [comment]
Yes @jmschrei 

```py
import numpy as np
import scipy.stats

class PowerLawDistribution():
    """
    Power Law Distribution
    """
    def __init__(self, a):
        self.a = a
        self.parameters = (self.a)
        self.d = 1
        self.summaries = numpy.zeros(3)

    def probability(self, X):
        return np.exp(self.log_probability(X))
        
    def log_probability(self, X):
        return scipy.stats.powerlaw.logpdf(X, self.a)

    def summarize(self, X, w=None):
        if w is None:
            w = numpy.ones(X.shape[0])

        X = X.reshape(X.shape[0])
        self.summaries[0] += w.sum()
        self.summaries[1] += X.dot(w)
        self.summaries[2] += (X ** 2.).dot(w)

    def from_summaries(self, inertia=0.0):
        self.mu = self.summaries[1] / self.summaries[0]
        self.std = self.summaries[2] / self.summaries[0] - self.summaries[1] ** 2 / (self.summaries[0] ** 2)
        self.std = numpy.sqrt(self.std)
        self.parameters = (self.mu, self.std)
        self.clear_summaries()

    def clear_summaries(self, inertia=0.0):
        self.summaries = numpy.zeros(3)

    @classmethod
    def from_samples(cls, X, weights=None, df=1):
        d = PowerLawDistribution(0)
        d.summarize(X, weights)
        d.from_summaries()
        return d

    @classmethod
    def blank(cls):
        return PowerLawDistribution(0)
```

So, I would like to fit the Gaussian distribution with the power-law distribution as follows:

```py
import numpy as np
X = np.hstack((np.random.power(0.5, size=10000), 
               np.random.randn(1000) + 5)) # example data
PowerLawDistribution.from_samples(X).parameters # works for me (parameter not correct)
```

However, when I tried `GeneralMixtureModel.from_samples`, I got the error:

```
model = GeneralMixtureModel.from_samples([PowerLawDistribution, NormalDistribution], n_components=2, 
                                         X=X, max_iterations=5)
```

Thanks so much for the quick response!

**Comment by titipata** [comment]
@jmschrei I updated the code and description respectively. Thanks a lot!

**Comment by jmschrei** [comment]
The data needs to be two dimensional. Even if you only have a single feature, it needs to be of shape `(n, 1)`. I get the following error with your code:

```
Traceback (most recent call last):
  File "test3.py", line 58, in <module>
    model = GeneralMixtureModel.from_samples([PowerLawDistribution, NormalDistribution], n_components=2, X=X, max_iterations=5)
  File "pomegranate/gmm.pyx", line 565, in pomegranate.gmm.GeneralMixtureModel.from_samples
ValueError: need more than 1 value to unpack
```

And I can fix it by reshaping the data to be the following:

```python
X = numpy.hstack((numpy.random.power(0.5, size=10000), 
               numpy.random.randn(1000) + 5)).reshape(-1, 1)
```

**Comment by titipata** [comment]
@jmschrei, I did that and it works. I'm wondering more about the `AttributeError: 'PowerLawDistribution' object has no attribute 'to_json'`. I also got the same error in the provided tutorial notebook.

**Comment by jmschrei** [comment]
It has something to do with the serialization, which can either be happening if you're trying to get a string representation of the model, or you're trying to copy it. It shouldn't be involved in doing either training or inference on a mixture model. I'm not sure off hand which one would be happening here. You could try implementing a `to_json` method.

**Comment by titipata** [comment]
@jmschrei thanks so much! So in the end adding `to_json` method solves the problem! Here, I put the code that (sort of) works for my specific use case below:

```py
class PowerLawDistribution():
    """
    Power Law Distribution
    """
    def __init__(self, a):
        self.a = a
        self.parameters = (self.a)
        self.d = 1
        self.summaries = numpy.zeros(3)
        self.frozen = True
        self.name = "PowerLawDistribution"

    def probability(self, X):
        return numpy.exp(self.log_probability(X))
        
    def log_probability(self, X):
        return scipy.stats.powerlaw.logpdf(X, self.a)

    def summarize(self, X, w=None):
        if w is None:
            w = numpy.ones(X.shape[0])

        X = X.reshape(X.shape[0])
        self.summaries[0] += w.sum()
        self.summaries[1] += X.dot(w)
        self.summaries[2] += (X ** 2.).dot(w)

    def from_summaries(self, inertia=0.0):
        self.a = 1 / ((1 / (self.summaries[1] / self.summaries[0])) - 1)
        self.parameters = (self.a)
        self.clear_summaries()

    def clear_summaries(self, inertia=0.0):
        self.summaries = numpy.zeros(3)

    @classmethod
    def from_samples(cls, X, weights=None, df=1):
        d = PowerLawDistribution(0)
        d.summarize(X, weights)
        d.from_summaries()
        return d

    @classmethod
    def blank(cls):
        return PowerLawDistribution(0)
    
    def to_json(self, separators=(',', ' : '), indent=4):
        """Convert the distribution to JSON format."""
        return json.dumps({'class' : 'Distribution', 
                           'name': self.name,
                           'frozen': self.frozen, 
                           'parameters': self.parameters}, 
                          separators=separators, 
                          indent=indent)
```


```py
# example data
X = np.concatenate((np.random.power(0.1, size=1000), (np.random.randn(1000) + 5))).reshape(-1, 1)

# 
model = GeneralMixtureModel.from_samples([PowerLawDistribution, NormalDistribution], 
                                         n_components=2, X=X)

>> 
{
    "class" : "GeneralMixtureModel",
    "distributions" : [
        {
            "class" : "Distribution",
            "name" : "PowerLawDistribution",
            "frozen" : true,
            "parameters" : 0.09644817865134457
        },
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                5.01604723155101,
                1.0674845155228598
            ],
            "frozen" : false
        }
    ],
    "weights" : [
        0.49996047017237033,
        0.5000395298276297
    ]
}
```

I think it would be great to update the [C_Feature_Tutorial_5_Custom_Distributions](https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb) notebook. Currently, following the documentation will give an error due to this `to_json` method. It would be nice to clarify what needs to be specified in creating the distribution e.g. `self.name`, `self.frozen`, and all the methods needed.
