### ISSUE TITLE
`HiddenMarkovModel.from_samples` fails if some of the labels are `None`

### ISSUE THREAD

**Issue by paulbrodersen** [jmschrei/pomegranate#592]
Hi Jacob

I am running into some issues when trying to fit a `HiddenMarkovModel` to labeled data where some of the **labels** are missing. 

## MWE

```python
#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
from pomegranate import (MultivariateGaussianDistribution,
                         State,
                         HiddenMarkovModel)


def generate_random_mvn_distribution(d=3, k=2):
    """
    Returns means and covariance matrix for a multivariate normal distribution
    with a specified number of dimensions.

    Arguments:
    ----------
    d: int > 1
        Dimensionality of the MVN distribution

    k: int > 0
        Number of independent factor loadings in the covariance matrix;
        see https://stats.stackexchange.com/a/125020/158806 for details

    Adapted from:
    -------------
    https://stats.stackexchange.com/a/125020/158806

    See also:
    ---------
    https://stats.stackexchange.com/questions/2746/how-to-efficiently-generate-random-positive-semidefinite-correlation-matrices
    """

    # compute mu
    mu = np.random.randn(d)

    # compute cov
    u = np.random.randn(d, k)              # generate samples from 'factors'
    v = np.dot(u, u.T)                     # generate rank deficient covariance matrix
    w = v + np.diag(np.random.rand(1, d))  # make full rank
    x = np.diag(1./np.sqrt(np.diag(v)))    # normalize
    cov = np.dot(np.dot(x, w), x)

    return mu, cov


if __name__ == '__main__':

    print('Generating MVN distributions...')
    d1 = MultivariateGaussianDistribution(*generate_random_mvn_distribution(d=3))
    d2 = MultivariateGaussianDistribution(*generate_random_mvn_distribution(d=3))

    print("Initialising HMM")
    s1 = State(d1, 's1')
    s2 = State(d2, 's2')

    # transition probability matrix
    Q = np.array([[0.9, 0.1],
                  [0.1, 0.9]])

    model = HiddenMarkovModel()
    model.add_state(s1)
    model.add_state(s2)

    model.add_transition(model.start, s1, 0.5)
    model.add_transition(model.start, s2, 0.5)
    model.add_transition(model.end, s1, 0.5)
    model.add_transition(model.end, s2, 0.5)

    model.add_transition(s1, s1, Q[0,0])
    model.add_transition(s1, s2, Q[0,1])
    model.add_transition(s2, s1, Q[1,0])
    model.add_transition(s2, s2, Q[1,1])
    model.bake()
    # print(model)

    print("Simulating sequence")
    (samples, simulated_path), = model.sample(1, 100, path=True)

    # parse simulated path to recover state labels
    labels = [state.name for state in simulated_path[1:]]

    # change some labels to None
    labels[1] = None

    print("Fitting new model to the data...")
    fitted_model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=2,
                                                  X=[samples], labels=[labels], algorithm='labeled', state_names=list(set(labels)))

    # determin Viterbi path
    logp, inferred_path = fitted_model.viterbi(samples)

    state_to_int = {'s1': 0, 's2' : 1}
    simulated_path = [state_to_int[state.name] for state in simulated_path[1:]]
    inferred_path  = [state_to_int[state.name] for (_, state) in inferred_path[1:]]

    print("Plotting...")

    fig, ax = plt.subplots(1,1)
    ax.plot(np.array(simulated_path))
    ax.plot(np.array(inferred_path) + 1.1)

    plt.ion()
    plt.show()
    input("Press any key to close figures...")
    plt.close('all')

```

Running this script fails when trying to fit the model with the following error message:
```shell
  File "somnotate/mwe_missing_labels.py", line 93, in <module>
    X=[samples], labels=[labels], algorithm='labeled', verbose=True)
  File "pomegranate/hmm.pyx", line 3624, in pomegranate.hmm.HiddenMarkovModel.from_samples
  File "/home/paul/.virtualenvs/somnotate3/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 264, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/home/paul/.virtualenvs/somnotate3/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 312, in _unique1d
    ar.sort()
```

The problem seems to lie in lines 3617-3625 of hmm.pyx:
```python
        if labels is not None:
            X_ = [x for x, label in zip(X, labels) if label != None]
            X_ = numpy.concatenate(X_)

            labels_ = numpy.concatenate([l for l in labels if l is not None])

            labels_ = numpy.array([l for l in labels_ if l != str(name)+"-start" and l != str(name)+"-end"])
            label_set = numpy.unique(labels_)
```

The assumption in the code seems to be that `labels` is a flat list, whereas it actually is (and has to be) a nested list. 

IMO, these should read instead:

```python
        if labels is not None:
            # flatten list of sequences while excluding sequences without labels
            X_ = numpy.concatenate([x for x, l in zip(X, labels) if l is not None])
            labels_ = numpy.concatenate([l for l in labels if l is not None])

            # exclude samples without labels
            X_ = numpy.array([x for x, label in zip(X_, labels_) if label is not None])
            labels_ = numpy.array([label for label in labels_ if label is not None])

            labels_ = numpy.array([l for l in labels_ if l != str(name)+"-start" and l != str(name)+"-end"])
            label_set = numpy.unique(labels_)
```

That patch kind of works in as much as the model can be fitted and the fitted model finds the correct Viterbi path in an unlabeled sequence. However, during fitting a lot of KeyErrors seems to occur in `_labeled_summarize`:

```shell
KeyError: 's2'
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: s2
KeyError: 's2'
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: s2
```
In other words, some assumption about the state names seems to be violated. For non-toy data, in most cases the VIterbi path seem to be fine, but in a minority of cases one of the states is completely mislabeled. 

Also, in a small number of cases, the Viterbi path all of the sudden contains UUID sequences?!

```shell
Traceback (most recent call last):
  File "somnotate/mwe_missing_labels.py", line 94, in <module>
    inferred_path  = [state_to_int[state.name] for (_, state) in inferred_path[1:]]
  File "somnotate/mwe_missing_labels.py", line 94, in <listcomp>
    inferred_path  = [state_to_int[state.name] for (_, state) in inferred_path[1:]]
KeyError: 'b5f119a0-cd6c-46aa-b1bf-cd121d2c48d1'
```

I have no idea where those UUIDs are coming from, and even after staring at `_labeled_summarize` for an extended amount of time I have no clue what might be going wrong there (either?). I hope and suspect that you have some intuition what might be the underlying cause. 

Best,
Paul

**Comment by paulbrodersen** [comment]
Potentially related: #529

**Comment by jmschrei** [comment]
pomegranate currently doesn't support the case where some labels within a single sequence are missing. It only supports the case where some sequences are labeled and others are not. Sorry!
