### ISSUE TITLE
Multivariate HMM: Leading minor of the array is not positive definite

### ISSUE THREAD

**Issue by m-decoster** [jmschrei/pomegranate#615]
I'm opening a new issue for this since the original reporter has not reopened #478.

This error still exists on 0.11.1, so updating pomegranate does not help.

```
import pomegranate as pg
import numpy as np

n = 4
d = 1000
x = np.random.randint(2, size=(n, d), dtype=bool)
x[3] = x[1] & x[2]
X = [x]

model = pg.HiddenMarkovModel.from_samples(
    pg.MultivariateGaussianDistribution,
    n_components=2, X=X,
    verbose=True)
```

I actually tried a more complicated case first, but even this simple example does not work, which I found in #478.

**Comment by jmschrei** [comment]
This is a somewhat difficult issue for me to address because simply running `numpy.cov(x)` on that example raises the same error. I could add in more default regularization of the covariance matrix in this case to try to account for it, but I think there will always be problems with trying to estimate covariance matrices from with large numbers of dimensions and small numbers of examples. Sorry that I couldn't get to this issue earlier.

**Comment by kisudsoe** [comment]
Hi, I am using 0.14.5 version, but it looks like that this issue still remains.
Below is my error code with the same example code.

```
Traceback (most recent call last):
  File "pomegranate/distributions/MultivariateGaussianDistribution.pyx", line 261, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries
  File "/usr/local/lib/python3.8/dist-packages/scipy/linalg/decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
  File "/usr/local/lib/python3.8/dist-packages/scipy/linalg/decomp_cholesky.py", line 37, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pomegranate/hmm.pyx", line 3664, in pomegranate.hmm.HiddenMarkovModel.from_samples
  File "pomegranate/distributions/MultivariateGaussianDistribution.pyx", line 294, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_samples
  File "pomegranate/distributions/distributions.pyx", line 155, in pomegranate.distributions.distributions.Distribution.fit
  File "pomegranate/distributions/MultivariateGaussianDistribution.pyx", line 269, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
