### ISSUE TITLE
Complex Number in GeneralMixtureModel/ MultivariateGaussianDistribution

### ISSUE THREAD

**Issue by nilsroth** [jmschrei/pomegranate#633]
Hi,

I got the following error when trying to fit a GeneralMixtureModel with multiple MultivariateGaussianDistributions:
```python
TypeError: Cannot cast ufunc subtract output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
Full Traceback:
```python
Traceback (most recent call last):

  File "<ipython-input-18-b1e3f6d42f9c>", line 2, in <module>
    pg.GeneralMixtureModel.from_samples(pg.MultivariateGaussianDistribution, n_components = N_COMPONENTS, X = dataset, verbose = False)

  File "pomegranate/gmm.pyx", line 616, in pomegranate.gmm.GeneralMixtureModel.from_samples

  File "pomegranate/distributions/MultivariateGaussianDistribution.pyx", line 302, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_samples

  File "pomegranate/distributions/distributions.pyx", line 156, in pomegranate.distributions.distributions.Distribution.fit

  File "pomegranate/distributions/MultivariateGaussianDistribution.pyx", line 277, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries

TypeError: Cannot cast ufunc subtract output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```

It seems like that the Eigenvalue decomposition can produce complex numbers and therefore cause this error (line 276-277 in MultivariateGaussianDistribution.pyx)
```python
min_eig = numpy.linalg.eig(self.cov)[0].min()
self.cov -= numpy.eye(d) * (min_eig - eps)
```
The same error can be provoked with this minimal example:
```python
a = np.array(1+1j)
b = np.array(1.0)
b -= a
```

It seems that this error is some kind of edge case as it appears only in some specific cases and is depended on the initialization of random numbers (probably related to Kmeans?) However, I was able to find a small section of my dataset [gmm_fails_complex128_dataset.txt](https://github.com/jmschrei/pomegranate/files/3717113/gmm_fails_complex128_dataset.txt) (which contains 2x3 axis IMU signals) that can reproduce this error with the following snippet:
```python
import pomegranate as pg
import numpy as np

dataset = np.loadtxt('gmm_fails_complex128_dataset.txt',delimiter=',')

N_COMPONENTS = 8

# this code generates a model as expected
np.random.seed(1)
pg.GeneralMixtureModel.from_samples(pg.MultivariateGaussianDistribution, n_components = N_COMPONENTS, X = dataset, verbose = False)

#this code fails
np.random.seed(0)
pg.GeneralMixtureModel.from_samples(pg.MultivariateGaussianDistribution, n_components = N_COMPONENTS, X = dataset, verbose = False)
```
Any thoughts why this happens?

**Comment by jmschrei** [comment]
pomegranate does not support complex numbers.

**Comment by nilsroth** [comment]
Ok. Thanks for your answer. However, I actually do not intent to work with complex numbers and all my data are just real numbers (floats). However pomegranate seems to generate complex numbers internally?

**Comment by jmschrei** [comment]
I've seen this in a few examples. I'm not precisely sure what's happening but suspect that it's a result of the cholesky decomposition I do for the covariance matrix estimation. I don't know what your data looks like but I suspect it has a large number of dimensions and a small number of examples. In these cases, it can be difficult to accurately estimate the covariance matrix.

**Comment by jzyhywxz** [comment]
@nilsroth @jmschrei Hi, I meet the same problem when I use the MultivariateGaussianDistribution, below is the code snippet:
```python
    data = x_with_state[i].astype(np.float64)
    print(type(data), data.shape)
    d = MultivariateGaussianDistribution.from_samples(data)
```
and the output is as follows:
```
<class 'numpy.ndarray'> (335, 56)
Traceback (most recent call last):
  File "pomegranate\distributions\MultivariateGaussianDistribution.pyx", line 264, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries
  File "C:\Users\xxx\anaconda3\lib\site-packages\scipy\linalg\decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "C:\Users\xxx\anaconda3\lib\site-packages\scipy\linalg\decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.LinAlgError: 5-th leading minor of the array is not positive definite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/Xxx/hmm/HMM.py", line 90, in <module>
    emission, transition = get_emission_and_transition_proba(train_dir, n_classes=n_classes)
  File "C:/Users/xxx/PycharmProjects/Xxx/hmm/HMM.py", line 74, in get_emission_and_transition_proba
    d = MultivariateGaussianDistribution.from_samples(data)
  File "pomegranate\distributions\MultivariateGaussianDistribution.pyx", line 297, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_samples
  File "pomegranate\distributions\distributions.pyx", line 156, in pomegranate.distributions.distributions.Distribution.fit
  File "pomegranate\distributions\MultivariateGaussianDistribution.pyx", line 272, in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
I think this is an interval bug of **pomegranate**, but I am a freshman of **pomegranate**, can everyone help me? Thanks.

**Comment by jzyhywxz** [comment]
Moreover, I find that the covariance output by **pomegranate** does not equal to that output by **NumPy**. The code snippet is:
```python
    print('pomegranate.__version__', pomegranate.__version__)
    print('numpy.__version__', np.__version__)

    x = numpy.random.normal(10, 1, size=(1000, 3))

    d = MultivariateGaussianDistribution.from_samples(x)
    print('d.mu', d.mu.shape, d.mu)
    print('d.cov', d.cov.shape, d.cov)

    m = np.mean(x, axis=0)
    c = np.cov(x.T)
    print('m', m.shape, m)
    print('c', c.shape, c)
```
and the output is:
```
pomegranate.__version__ 0.12.2
numpy.__version__ 1.18.1
d.mu (3,) [10.00114835 10.00043014 10.01952582]
d.cov (3, 3) [[ 0.96693154 -0.00508092 -0.00619132]
 [-0.00508092  0.8874858   0.03042675]
 [-0.00619132  0.03042675  1.01313561]]
m (3,) [10.00114835 10.00043014 10.01952582]
c (3, 3) [[ 0.96789944 -0.005086   -0.00619751]
 [-0.005086    0.88837417  0.03045721]
 [-0.00619751  0.03045721  1.01414976]]
```
As we can see, the mean vector produced by **pomegranate** is the same as that produced by **NumPy**, but the covariance produced by **pomegranate** is slightly different from that produced by **NumPy**.
I think this may be one of the possible reasons to raise the above-mentioned bug.

**Comment by arkincognito** [comment]
Still having the issue with MultivariateGaussianDistribution.

```python
import pomegranate as pm

pmhmm = pm.HiddenMarkovModel.from_samples(pm.distributions.MultivariateGaussianDistribution, n_components=NUM_HIDDEN_STATE, X=obs, labels=hs, algorithm='baum-welch', init="random", n_jobs=-1)
```
where `obs` is multivariate observations in real numbers and `hs` is hidden states in integers.
I'm getting 
```python
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pomegranate/distributions/MultivariateGaussianDistribution.pyx in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries()

7 frames
/usr/local/lib/python3.7/dist-packages/scipy/linalg/decomp_cholesky.py in cholesky(a, lower, overwrite_a, check_finite)
     90     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
---> 91                          check_finite=check_finite)
     92     return c

/usr/local/lib/python3.7/dist-packages/scipy/linalg/decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     39         raise LinAlgError("%d-th leading minor of the array is not positive "
---> 40                           "definite" % info)
     41     if info < 0:

LinAlgError: 17-th leading minor of the array is not positive definite

During handling of the above exception, another exception occurred:

UFuncTypeError                            Traceback (most recent call last)
<ipython-input-40-cd0dad296b9a> in <module>()
      1 import pomegranate as pm
      2 
----> 3 pmhmm = pm.HiddenMarkovModel.from_samples(pm.distributions.MultivariateGaussianDistribution, n_components=NUM_HIDDEN_STATE, X=obs, labels=hs, algorithm='viterbi', init="random", n_jobs=-1)
      4 # pmhmm.bake()
      5 # pmhmm.fit(sequences=obs, labels=hs, algorithm="baum-welch")

/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm._initialize_distributions()

/usr/local/lib/python3.7/dist-packages/pomegranate/distributions/MultivariateGaussianDistribution.pyx in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_samples()

/usr/local/lib/python3.7/dist-packages/pomegranate/distributions/distributions.pyx in pomegranate.distributions.distributions.Distribution.fit()

/usr/local/lib/python3.7/dist-packages/pomegranate/distributions/MultivariateGaussianDistribution.pyx in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.from_summaries()

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
Seems like HiddenMarkovModel.from_samples internally generates complex128 values.

**Comment by teoML** [comment]
@arkincognito , did you find a solution to that problem?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.

**Comment by anneborcherding** [comment]
Hi there, thank you for the remake of pomegranate!

I am currently using version v1.1.0, and I receive a similar error (see below for a full stack trace):

```
_LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 15 is not positive-definite).
```

I used the following code to define my HMM:

```
from pomegranate.hmm import DenseHMM
from pomegranate.distributions import Normal

no_hmm = 7
node_distributions = [Normal() for _ in range(no_hmm)]
model = DenseHMM(node_distributions, verbose=True)
model.fit(data)
```

The data used in the code snippet is this (dumped with joblib, can be loaded with `joblib.load("hmm_data.dmp")`:
[hmm_data.dmp](https://github.com/user-attachments/files/16349983/hmm_data.dmp)

Stack Trace:

```
File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py:616](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py#line=615), in _BaseHMM.fit(self, X, sample_weight, priors)
    614 if not self._initialized:
    615 	if sample_weight is None:
--> 616 		self._initialize(X)
    617 	else:
    618 		self._initialize(X, sample_weight=sample_weight)

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/dense_hmm.py:163](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/dense_hmm.py#line=162), in DenseHMM._initialize(self, X, sample_weight)
    144 def _initialize(self, X=None, sample_weight=None):
    145 	"""Initialize the probability distribution.
    146 
    147 	This method is meant to only be called internally. It initializes the
   (...)
    160 		Default is None.
    161 	"""
--> 163 	super()._initialize(X, sample_weight=sample_weight)
    165 	n = self.n_distributions
    166 	if self.edges == None:

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py:240](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py#line=239), in _BaseHMM._initialize(self, X, sample_weight)
    237 y_hat = model.fit_predict(X, sample_weight=sample_weight)
    239 for i in range(self.n_distributions):
--> 240 	self.distributions[i].fit(X[y_hat == i].cpu(), 
    241 		sample_weight=sample_weight[y_hat == i].cpu())
    242 	self.distributions[i].to(X.device)
    244 self.d = X.shape[-1]

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/_distribution.py:76](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/_distribution.py#line=75), in Distribution.fit(self, X, sample_weight)
     74 def fit(self, X, sample_weight=None):
     75 	self.summarize(X, sample_weight=sample_weight)
---> 76 	self.from_summaries()
     77 	return self

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py:300](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py#line=299), in Normal.from_summaries(self)
    298 _update_parameter(self.means, means, self.inertia)
    299 _update_parameter(self.covs, covs, self.inertia)
--> 300 self._reset_cache()

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py:144](http://localhost:8889/home/borche/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py#line=143), in Normal._reset_cache(self)
    140 self.register_buffer("_xxw_sum", torch.zeros(self.d, self.d, 
    141 	dtype=self.dtype, device=self.device))
    143 if self.covs.sum() > 0.0:
--> 144 	chol = torch.linalg.cholesky(self.covs)
    145 	_inv_cov = torch.linalg.solve_triangular(chol, torch.eye(
    146 		len(self.covs), dtype=self.dtype, device=self.device), 
    147 		upper=False).T
    148 	_inv_cov_dot_mu = torch.matmul(self.means, _inv_cov)
```

**Comment by anneborcherding** [comment]
Hi there, thank you for the remake of pomegranate!

I am currently using version v1.1.0, and I receive a similar error (see below for a full stack trace):

```
_LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 15 is not positive-definite).
```

I used the following code to define my HMM:

```
from pomegranate.hmm import DenseHMM
from pomegranate.distributions import Normal

no_hmm = 5
node_distributions = [Normal() for _ in range(no_hmm)]
model = DenseHMM(node_distributions, verbose=True)
model.fit(data)
```

The data used in the code snippet is this (dumped with joblib, can be loaded with `joblib.load("hmm_data.dmp")`:
[hmm_data.dmp](https://github.com/user-attachments/files/16349983/hmm_data.dmp)

Stack Trace:

```
File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py:616](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py#line=615), in _BaseHMM.fit(self, X, sample_weight, priors)
    614 if not self._initialized:
    615 	if sample_weight is None:
--> 616 		self._initialize(X)
    617 	else:
    618 		self._initialize(X, sample_weight=sample_weight)

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/dense_hmm.py:163](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/dense_hmm.py#line=162), in DenseHMM._initialize(self, X, sample_weight)
    144 def _initialize(self, X=None, sample_weight=None):
    145 	"""Initialize the probability distribution.
    146 
    147 	This method is meant to only be called internally. It initializes the
   (...)
    160 		Default is None.
    161 	"""
--> 163 	super()._initialize(X, sample_weight=sample_weight)
    165 	n = self.n_distributions
    166 	if self.edges == None:

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py:240](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/hmm/_base.py#line=239), in _BaseHMM._initialize(self, X, sample_weight)
    237 y_hat = model.fit_predict(X, sample_weight=sample_weight)
    239 for i in range(self.n_distributions):
--> 240 	self.distributions[i].fit(X[y_hat == i].cpu(), 
    241 		sample_weight=sample_weight[y_hat == i].cpu())
    242 	self.distributions[i].to(X.device)
    244 self.d = X.shape[-1]

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/_distribution.py:76](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/_distribution.py#line=75), in Distribution.fit(self, X, sample_weight)
     74 def fit(self, X, sample_weight=None):
     75 	self.summarize(X, sample_weight=sample_weight)
---> 76 	self.from_summaries()
     77 	return self

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py:300](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py#line=299), in Normal.from_summaries(self)
    298 _update_parameter(self.means, means, self.inertia)
    299 _update_parameter(self.covs, covs, self.inertia)
--> 300 self._reset_cache()

File [~/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py:144](http://localhost:8889/home/XX/miniconda3/envs/behavior_modeling_new/lib/python3.10/site-packages/pomegranate/distributions/normal.py#line=143), in Normal._reset_cache(self)
    140 self.register_buffer("_xxw_sum", torch.zeros(self.d, self.d, 
    141 	dtype=self.dtype, device=self.device))
    143 if self.covs.sum() > 0.0:
--> 144 	chol = torch.linalg.cholesky(self.covs)
    145 	_inv_cov = torch.linalg.solve_triangular(chol, torch.eye(
    146 		len(self.covs), dtype=self.dtype, device=self.device), 
    147 		upper=False).T
    148 	_inv_cov_dot_mu = torch.matmul(self.means, _inv_cov)
```
