### ISSUE TITLE
TypeError when training HMM with mixture and labeled states

### ISSUE THREAD

**Issue by gioschibo** [jmschrei/pomegranate#659]
Hi! When I attempt to train a HMM with a mixture model of multivariate gaussians and providing labeled states, I get a TypeError stating that it cannot convert a numpy.float64 to a numpy.ndarray. The error could be related to #111.

This is the output:

> Traceback (most recent call last):
  File "/Users/GS/ownCloud/greenTEG/framework/HMM_training.py", line 57, in <module>
    hmm.gmmhmm_training(hmm_model, arr_data_all, arr_cpt_all)
  File "/Users/GS/ownCloud/greenTEG/framework/HMM_tools.py", line 88, in gmmhmm_training
    model.fit(X_train, labels=label_states, algorithm='labeled')
  File "pomegranate/hmm.pyx", line 2544, in pomegranate.hmm.HiddenMarkovModel.fit
  File "pomegranate/hmm.pyx", line 2586, in pomegranate.hmm.HiddenMarkovModel.fit
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "pomegranate/hmm.pyx", line 2696, in pomegranate.hmm.HiddenMarkovModel.summarize
TypeError: Cannot convert numpy.float64 to numpy.ndarray

The code i am using is the following:

    model = pom.HiddenMarkovModel()

    states = []
    for istate, state_bin in enumerate(state_bins):
        mixtures = [pom.distributions.MultivariateGaussianDistribution(means[state_bin][imix], np.identity(ndimensions))
                        for imix in range(nmixtures)]
`states.append(pom.State(pom.GeneralMixtureModel(mixtures),name=str(state_bin)))`
      
        model.add_state(states[istate])

    for state in range(nstates):
        if state == 0:
            model.add_transition(model.start, states[state], 1)
        model.add_transition(states[state], states[state], 0.8)
        if state == 0:
            nextstate = state + 1
            model.add_transition(states[state], states[nextstate], 0.1)
            nextstate = state + 2
            model.add_transition(states[state], states[nextstate], 0.1)
        elif state == 1:
            nextstate = state + 1
            model.add_transition(states[state], states[nextstate], 0.1)
            nextstate = state + 2
            model.add_transition(states[state], states[nextstate], 0.1)
            prevstate = state - 1
            model.add_transition(states[state], states[prevstate], 0.1)
        elif state == nstates - 1:
            prevstate = state - 1
            model.add_transition(states[state], states[prevstate], 0.1)
            prevstate = state - 2
            model.add_transition(states[state], states[prevstate], 0.1)
        elif state == nstates - 2:
            nextstate = state + 1
            model.add_transition(states[state], states[nextstate], 0.1)
            prevstate = state - 1
            model.add_transition(states[state], states[prevstate], 0.1)
            prevstate = state - 2
            model.add_transition(states[state], states[prevstate], 0.1)
        else:
            nextstate = state + 1
            model.add_transition(states[state], states[nextstate], 0.1)
            nextstate = state + 2
            model.add_transition(states[state], states[nextstate], 0.1)
            prevstate = state - 1
            model.add_transition(states[state], states[prevstate], 0.1)
            prevstate = state - 2
            model.add_transition(states[state], states[prevstate], 0.1)

    model.add_transition(states[nstates - 1], model.end, 0.2)
    model.bake()

    model.fit(X_train, labels=label_states, algorithm='labeled')

   
Just note that, if i run the function
`model.fit(X_train)` 
without labels, the code seems to work.

**Comment by gioschibo** [comment]
Update: I was feeding the labels_states as float. When i changed them in strings, as the name of the states i get the error:

> TypeError: Cannot convert numpy.str_ to numpy.ndarray
