### ISSUE TITLE
HMM error when merging silent states

### ISSUE THREAD

**Issue by resulknad** [jmschrei/pomegranate#671]
I've modified the global alignment model from B_Model_Tutorial_3_Hidden_Markov_Models.ipynb such that pomegranate will merge states. It will throw the following error:
```
Traceback (most recent call last):
  File "main2.py", line 68, in <module>
    model.bake(verbose = True)
  File "pomegranate/hmm.pyx", line 802, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/home/X/.local/share/virtualenvs/thomas3-6Yd0jBOf/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 669, in <genexpr>
    return (self._report(n, nbr, dd) for n, nbrs in (self._nodes_nbrs())
RuntimeError: dictionary changed size during iteration
```

The relevant code to reproduce the issue:
```
from pomegranate import * 

model = HiddenMarkovModel( "Global Alignment")

i_d = DiscreteDistribution( { 'A': 0.25, 'C': 0.25, 'G': 0.25, 'T': 0.25 } )

i0 = State( i_d, name="I0" )
i1 = State( i_d, name="I1" )
i2 = State( i_d, name="I2" )
i3 = State( i_d, name="I3" )

m1 = State( DiscreteDistribution({ "A": 0.95, 'C': 0.01, 'G': 0.01, 'T': 0.02 }) , name="M1" )
m2 = State( DiscreteDistribution({ "A": 0.003, 'C': 0.99, 'G': 0.003, 'T': 0.004 }) , name="M2" )
m3 = State( DiscreteDistribution({ "A": 0.01, 'C': 0.01, 'G': 0.01, 'T': 0.97 }) , name="M3" )

d1 = State( None, name="D1" )
d2 = State( None, name="D2" )
d3 = State( None, name="D3" )

model.add_states( [i0, i1, i2, i3, m1, m2, m3, d1, d2, d3 ] )

model.add_transition( model.start, m1, 0.9 )
model.add_transition( model.start, i0, 0.1 )
model.add_transition( m1, m2, 0.9 )
model.add_transition( m1, i1, 0.05 )
model.add_transition( m1, d2, 0.05 )
model.add_transition( m2, m3, 0.9 )
model.add_transition( m2, i2, 0.05 )
model.add_transition( m2, d3, 0.05 )
model.add_transition( m3, model.end, 0.9 )
model.add_transition( m3, i3, 0.1 )

model.add_transition( i0, i0, 0.70 )
model.add_transition( i0, d1, 0.15 )
model.add_transition( i0, m1, 0.15 )

model.add_transition( i1, i1, 0.70 )
model.add_transition( i1, d2, 0.15 )
model.add_transition( i1, m2, 0.15 )

model.add_transition( i2, i2, 0.70 )
model.add_transition( i2, d3, 0.15 )
model.add_transition( i2, m3, 0.15 )

model.add_transition( i3, i3, 0.85 )
model.add_transition( i3, model.end, 0.15 )

model.add_transition( d1, d2, 0 )
model.add_transition( d1, i1, 0 )
model.add_transition( d1, m2, 1.0 )

model.add_transition( d2, d3, 0 )
model.add_transition( d2, i2, 0 )
model.add_transition( d2, m3, 1.0 )

model.add_transition( d3, i3, 0.30 )
model.add_transition( d3, model.end, 0.70 )

model.bake(verbose = True)
```

Pipfile used:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pomegranate = ">=0.12"
networkx = ">=2.4"

[requires]
python_version = "3.7"
```

**Comment by jmschrei** [comment]
Fixed in 0.12.1.
