### ISSUE TITLE
[BUG] Non existing key error.

### ISSUE THREAD

**Issue by JoseZamora97** [jmschrei/pomegranate#678]
**Describe the bug**
Hi, I am facing with this error, in line **net.bake()**

````
Traceback (most recent call last):
  File "C:/Users/.../file.py", line 210, in <module>
    net.bake()
  File "pomegranate\BayesianNetwork.pyx", line 360, in pomegranate.BayesianNetwork.BayesianNetwork.bake
  File "pomegranate\distributions\ConditionalProbabilityTable.pyx", line 121, in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.bake
KeyError: (2, 0, 0)
````
pip show pomegranate indicates this version:
````
Name: pomegranate
Version: 0.12.0
````
My OS is Windows 10.

**To Reproduce**
````python
from pomegranate import BayesianNetwork, ConditionalProbabilityTable, DiscreteDistribution, State

v1 = DiscreteDistribution({0: 0.5, 1: 0.4, 2: 0.1})
v7 = DiscreteDistribution({0: 0.4, 1: 0.6})

v9 = ConditionalProbabilityTable([
    [0, 0, 0.7],
    [0, 1, 0.3],
    [1, 0, 0.5],
    [1, 1, 0.5]], [v7])

v0 = ConditionalProbabilityTable([
    [0, 0, 0.6],
    [0, 1, 0.3],
    [0, 2, 0.1],
    [1, 0, 0.3],
    [1, 1, 0.5],
    [1, 2, 0.2],
    [2, 0, 0.1],
    [2, 1, 0.4],
    [2, 2, 0.5]], [v1])

v8 = ConditionalProbabilityTable([
    [0, 0, 0.6],
    [0, 1, 0.4],
    [1, 0, 0.4],
    [1, 1, 0.6]
], [v7])

v2 = ConditionalProbabilityTable([
    [0, 0, 0.6],
    [0, 1, 0.3],
    [0, 2, 0.1],
    [1, 0, 0.3],
    [1, 1, 0.5],
    [1, 2, 0.2],
    [2, 0, 0.1],
    [2, 1, 0.4],
    [2, 2, 0.5]
], [v1])

v3 = ConditionalProbabilityTable([
    [0, 0, 0, 0, 0.08],
    [0, 0, 0, 1, 0.06],
    [0, 0, 0, 2, 0.04],
    [0, 0, 1, 0, 0.06],
    [0, 0, 1, 1, 0.04],
    [0, 0, 1, 2, 0.02],
    [0, 0, 2, 0, 0.04],
    [0, 0, 2, 1, 0.02],
    [0, 0, 2, 2, 0.02],
    [0, 1, 0, 0, 0.08],
    [0, 1, 0, 1, 0.06],
    [0, 1, 0, 2, 0.06],
    [0, 1, 1, 0, 0.06],
    [0, 1, 1, 1, 0.06],
    [0, 1, 1, 2, 0.02],
    [0, 1, 2, 0, 0.02],
    [0, 1, 2, 1, 0.02],
    [0, 1, 2, 2, 0.02],
    [0, 2, 0, 0, 0.04],
    [0, 2, 0, 1, 0.02],
    [0, 2, 0, 2, 0.02],
    [0, 2, 1, 0, 0.04],
    [0, 2, 1, 1, 0.02],
    [0, 2, 1, 2, 0.02],
    [0, 2, 2, 0, 0.02],
    [0, 2, 2, 1, 0.02],
    [0, 2, 2, 2, 0.02],
    [1, 0, 0, 0, 0.06],
    [1, 0, 0, 1, 0.06],
    [1, 0, 0, 2, 0.06],
    [1, 0, 1, 0, 0.06],
    [1, 0, 1, 1, 0.02],
    [1, 0, 1, 2, 0.02],
    [1, 0, 2, 0, 0.02],
    [1, 0, 2, 1, 0.02],
    [1, 0, 2, 2, 0.04],
    [1, 1, 0, 0, 0.02],
    [1, 1, 0, 1, 0.08],
    [1, 1, 0, 2, 0.06],
    [1, 1, 1, 0, 0.04],
    [1, 1, 1, 1, 0.06],
    [1, 1, 1, 2, 0.04],
    [1, 1, 2, 0, 0.02],
    [1, 1, 2, 1, 0.04],
    [1, 1, 2, 2, 0.02],
    [1, 2, 0, 0, 0.02],
    [1, 2, 0, 1, 0.08],
    [1, 2, 0, 2, 0.02],
    [1, 2, 1, 0, 0.04],
    [1, 2, 1, 1, 0.02],
    [1, 2, 1, 2, 0.02],
    [1, 2, 2, 0, 0.02],
    [1, 2, 2, 1, 0.02],
    [1, 2, 2, 2, 0.02],
    [2, 0, 0, 0, 0.02],
    [2, 0, 0, 1, 0.02],
    [2, 0, 0, 2, 0.02],
    [2, 0, 1, 0, 0.02],
    [2, 0, 1, 1, 0.02],
    [2, 0, 1, 2, 0.02],
    [2, 0, 2, 0, 0.02],
    [2, 0, 2, 1, 0.02],
    [2, 0, 2, 2, 0.02],
    [2, 1, 0, 0, 0.02],
    [2, 1, 0, 1, 0.04],
    [2, 1, 0, 2, 0.02],
    [2, 1, 1, 0, 0.02],
    [2, 1, 1, 1, 0.04],
    [2, 1, 1, 2, 0.06],
    [2, 1, 2, 0, 0.04],
    [2, 1, 2, 1, 0.02],
    [2, 1, 2, 2, 0.04],
    [2, 2, 0, 0, 0.04],
    [2, 2, 0, 1, 0.02],
    [2, 2, 0, 2, 0.08],
    [2, 2, 1, 0, 0.06],
    [2, 2, 1, 1, 0.06],
    [2, 2, 1, 2, 0.06],
    [2, 2, 2, 0, 0.06],
    [2, 2, 2, 1, 0.08],
    [2, 2, 2, 2, 0.06]
], [v0, v1, v2])

v4 = ConditionalProbabilityTable([
    [0, 0, 0.6],
    [0, 1, 0.3],
    [0, 2, 0.1],
    [1, 0, 0.1],
    [1, 1, 0.6],
    [1, 2, 0.3],
    [2, 0, 0.1],
    [2, 1, 0.3],
    [2, 2, 0.6]
], [v3])

v6 = ConditionalProbabilityTable([
    [0, 0, 0, 0.03],
    [0, 0, 1, 0.05],
    [0, 0, 2, 0.1],
    [0, 1, 0, 0.05],
    [0, 1, 1, 0.1],
    [0, 1, 2, 0.15],
    [0, 2, 0, 0.1],
    [0, 2, 1, 0.15],
    [0, 2, 2, 0.27],
    [1, 0, 0, 0.27],
    [1, 0, 1, 0.15],
    [1, 0, 2, 0.1],
    [1, 1, 0, 0.15],
    [1, 1, 1, 0.1],
    [1, 1, 2, 0.05],
    [1, 2, 0, 0.1],
    [1, 2, 1, 0.05],
    [1, 2, 2, 0.03]
], [v3, v4])

v5 = ConditionalProbabilityTable([
    [0, 0, 0, 0.03],
    [0, 0, 1, 0.05],
    [0, 0, 2, 0.1],
    [0, 1, 0, 0.05],
    [0, 1, 1, 0.1],
    [0, 1, 2, 0.15],
    [0, 2, 0, 0.1],
    [0, 2, 1, 0.15],
    [0, 2, 2, 0.27],
    [1, 0, 0, 0.27],
    [1, 0, 1, 0.15],
    [1, 0, 2, 0.1],
    [1, 1, 0, 0.15],
    [1, 1, 1, 0.1],
    [1, 1, 2, 0.05],
    [1, 2, 0, 0.1],
    [1, 2, 1, 0.05],
    [1, 2, 2, 0.03]
], [v3, v4])

net = BayesianNetwork(name="debug")

s0 = State(v0, name="v0")
s1 = State(v1, name="v1")
s2 = State(v2, name="v2")
s3 = State(v3, name="v3")
s4 = State(v4, name="v4")
s5 = State(v5, name="v5")
s6 = State(v6, name="v6")
s7 = State(v7, name="v7")
s8 = State(v8, name="v8")
s9 = State(v9, name="v9")

net.add_states(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9)

net.add_edge(s1, s0)
net.add_edge(s1, s2)
net.add_edge(s0, s3)
net.add_edge(s1, s3)
net.add_edge(s2, s3)
net.add_edge(s3, s4)
net.add_edge(s3, s5)
net.add_edge(s4, s5)
net.add_edge(s3, s6)
net.add_edge(s4, s6)
net.add_edge(s7, s8)
net.add_edge(s7, s9)

net.bake()
````

**Comment by JoseZamora97** [comment]
I just realize that in Conditional Probability Tables the last column values refers to the current variable.
