### ISSUE TITLE
[BUG] Error when using multiple ConditionalProbabilityTables in Bayes Net

### ISSUE THREAD

**Issue by migratingcub** [jmschrei/pomegranate#716]
Hello, 

I'm fairly new to python and machine learning, so please bare with me.

I'm getting the following error when I try to run my code:

> Traceback (most recent call last):
  >File "dummydata.py", line 87, in <module>
   > network.bake()
  >File "pomegranate\BayesianNetwork.pyx", line 325, in pomegranate.BayesianNetwork.BayesianNetwork.bake
 > File "pomegranate\distributions\ConditionalProbabilityTable.pyx", line 218, in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.joint
>IndexError: list index out of range

To reproduce the error, you can run the following code:
This is my first time writing anything in python and I'm also self taught with machine learning and pomegranate. Any help is appreciated!

```import os, math, json, array, ast
from flask import Flask, request, jsonify
from pomegranate import *

bowsData = DiscreteDistribution( {'Other': 0.333, 'Protection': 0.333, 'Actual Rent': 0.333} )
propertyTypeData = DiscreteDistribution( {'Healthcare': 0.333, 'Land': 0.333, 'Retail': 0.333} )
incomeExpenseData = ConditionalProbabilityTable(
	[['Other', 'Healthcare', 'INCOME', 0.5],
	 ['Other', 'Healthcare', 'EXPENSE', 0.0],
	 ['Protection', 'Healthcare', 'INCOME', 0.5],
	 ['Protection', 'Healthcare', 'EXPENSE', 1.0],
	 ['Actual Rent', 'Healthcare', 'INCOME', 0.5],
	 ['Actual Rent', 'Healthcare', 'EXPENSE', 0.0],
	 ['Other', 'Land', 'INCOME', 0.0],
	 ['Other', 'Land', 'EXPENSE', 0.5],
	 ['Protection', 'Land', 'INCOME', 1.0],
	 ['Protection', 'Land', 'EXPENSE', 0.0],
	 ['Actual Rent', 'Land', 'INCOME', 0.5],
	 ['Actual Rent', 'Land', 'EXPENSE', 1.0],
	 ['Other', 'Retail', 'INCOME', 0.5],
	 ['Other', 'Retail', 'EXPENSE', 0.0],
	 ['Protection', 'Retail', 'INCOME', 0.0],
	 ['Protection', 'Retail', 'EXPENSE', 0.0],
	 ['Actual Rent', 'Retail', 'INCOME', 1.0],
	 ['Actual Rent', 'Retail', 'EXPENSE', 0.5]], [bowsData, propertyTypeData])
standardLineItemData = ConditionalProbabilityTable(
	[['Other', 'Healthcare', 'INCOME', 'Base Rent', 0.5],
	 ['Other', 'Healthcare', 'EXPENSE', 'Base Rent', 0.0],
	 ['Protection', 'Healthcare', 'INCOME', 'Base Rent', 0.5],
	 ['Protection', 'Healthcare', 'EXPENSE', 'Base Rent', 1.0],
	 ['Actual Rent', 'Healthcare', 'INCOME', 'Base Rent', 0.5],
	 ['Actual Rent', 'Healthcare', 'EXPENSE', 'Base Rent', 0.0],
	 ['Other', 'Land', 'INCOME', 'Base Rent', 0.0],
	 ['Other', 'Land', 'EXPENSE', 'Base Rent', 0.5],
	 ['Protection', 'Land', 'INCOME', 'Base Rent', 1.0],
	 ['Protection', 'Land', 'EXPENSE', 'Base Rent', 0.0],
	 ['Actual Rent', 'Land', 'INCOME', 'Base Rent', 0.5],
	 ['Actual Rent', 'Land', 'EXPENSE', 'Base Rent', 1.0],
	 ['Other', 'Retail', 'INCOME', 'Base Rent', 0.5],
	 ['Other', 'Retail', 'EXPENSE', 'Base Rent', 0.0],
	 ['Protection', 'Retail', 'INCOME', 'Base Rent', 0.0],
	 ['Protection', 'Retail', 'EXPENSE', 'Base Rent', 0.0],
	 ['Actual Rent', 'Retail', 'INCOME', 'Base Rent', 1.0],
	 ['Actual Rent', 'Retail', 'EXPENSE', 'Base Rent', 0.5],
	 ['Other', 'Healthcare', 'INCOME', 'Actual Rent', 0.5],
	 ['Other', 'Healthcare', 'EXPENSE', 'Actual Rent', 0.0],
	 ['Protection', 'Healthcare', 'INCOME', 'Actual Rent', 0.5],
	 ['Protection', 'Healthcare', 'EXPENSE', 'Actual Rent', 1.0],
	 ['Actual Rent', 'Healthcare', 'INCOME', 'Actual Rent', 0.5],
	 ['Actual Rent', 'Healthcare', 'EXPENSE', 'Actual Rent', 0.0],
	 ['Other', 'Land', 'INCOME', 'Actual Rent', 0.0],
	 ['Other', 'Land', 'EXPENSE', 'Actual Rent', 0.5],
	 ['Protection', 'Land', 'INCOME', 'Actual Rent', 1.0],
	 ['Protection', 'Land', 'EXPENSE', 'Actual Rent', 0.0],
	 ['Actual Rent', 'Land', 'INCOME', 'Actual Rent', 0.5],
	 ['Actual Rent', 'Land', 'EXPENSE', 'Actual Rent', 1.0],
	 ['Other', 'Retail', 'INCOME', 'Actual Rent', 0.5],
	 ['Other', 'Retail', 'EXPENSE', 'Actual Rent', 0.0],
	 ['Protection', 'Retail', 'INCOME', 'Actual Rent', 0.0],
	 ['Protection', 'Retail', 'EXPENSE', 'Actual Rent', 0.0],
	 ['Actual Rent', 'Retail', 'INCOME', 'Actual Rent', 1.0],
	 ['Actual Rent', 'Retail', 'EXPENSE', 'Actual Rent', 0.5]], [incomeExpenseData])

print("bowsData:")
print(bowsData)

print("propertyTypeData:")
print(propertyTypeData)

print("incomeExpenseData:")
print(incomeExpenseData)

print("standardLineItemData:")
print(standardLineItemData)

d1 = State(bowsData, name="bowsData")
d2 = State(propertyTypeData, name="propertyTypeData")
d3 = State(incomeExpenseData, name="incomeExpenseData")
d4 = State(standardLineItemData, name="standardLineItemData")

#Building the Bayesian Network
network = BayesianNetwork( "Digestible data..." )
network.add_states(d1, d2, d3, d4)
network.add_edge(d1, d3)
network.add_edge(d2, d3)
network.add_edge(d3, d4)
network.bake()

**Comment by jmschrei** [comment]
Howdy

Each conditional probability table represents a single variable (the one encoded in the last column before the probabilities), not a collection of variables. When you're defining the parents of the table it needs to include each of the parent variables. So, standardLineItemData should have the parents `[bowsData, propertyTypeData, incomeExpenseData]`.

**Comment by migratingcub** [comment]
That worked much better. Thank you!
