### ISSUE TITLE
Error when baking Bayesian Network

### ISSUE THREAD

**Issue by TomasRibeiro96** [jmschrei/pomegranate#743]
Hi!
I'm using pomegranate for my Bayesian Network but I'm getting an error when I try to bake it. I'm getting the following error message:
```
Traceback (most recent call last):
  File "/home/tomas/ros_ws/src/ROSPlan/src/rosplan/rosplan_demos/rosplan_csp_exec_demo/query_client2_pomegranate.py", line 1213, in <module>
    print(calculate_plan_probability_server())
  File "/home/tomas/ros_ws/src/ROSPlan/src/rosplan/rosplan_demos/rosplan_csp_exec_demo/query_client2_pomegranate.py", line 1206, in calculate_plan_probability_server
    return handle_request(original_plan)
  File "/home/tomas/ros_ws/src/ROSPlan/src/rosplan/rosplan_demos/rosplan_csp_exec_demo/query_client2_pomegranate.py", line 1036, in handle_request
    model.bake()
  File "pomegranate/BayesianNetwork.pyx", line 323, in pomegranate.BayesianNetwork.BayesianNetwork.bake
KeyError: {
    "table" : [
        [
            "T",
            "T",
            "0.93"
        ],
        [
            "T",
            "F",
            "0.07"
        ],
        [
            "F",
            "T",
            "0.05"
        ],
        [
            "F",
            "F",
            "0.95"
        ]
    ],
    "parents" : [
        {
            "frozen" : false,
            "dtype" : "str",
            "class" : "Distribution",
            "parameters" : [
                {
                    "T" : 1,
                    "F" : 0
                }
            ],
            "name" : "DiscreteDistribution"
        }
    ],
    "class" : "Distribution",
    "dtypes" : [
        "str",
        "str",
        "float"
    ],
    "name" : "ConditionalProbabilityTable"
}
```

To build the network, I'm using the following function:
```
def build_network(model, all_nodes, actions_par_child, predicates_par_child):
    nodes_dict = dict()
    for node_name in all_nodes:        
        cpd = cpds_map[node_name]
        node = Node(cpd, name=node_name)
        nodes_dict[node_name] = node
        model.add_node(node)

        if len(node_name.split('%')) > 1:
            parents_dict = predicates_par_child
        else:
            parents_dict = actions_par_child
        
        for parent in parents_dict[node_name]['parents']:
            parent_node = nodes_dict[parent]
            model.add_edge(parent_node, node)
```
It gets the CPD from the dictionary `cpds_map` and creates a node. Afterwards, it draws edges from its parents to the node (the first nodes of the network have no parents). All of the CPDs are defined in one of the following 3 ways:
```
cpd = DiscreteDistribution({'T': 1, 'F': 0})
cpds_map[pred_name] = cpd
```
```
pred_cpd = ConditionalProbabilityTable(
            [['T', 'T', 'T', effects_success],
             ['T', 'T', 'F', 1-effects_success],
             ['T', 'F', 'T', 1-spont_true_false],
             ['T', 'F', 'F', spont_true_false],
             ['F', 'T', 'T', effects_success],
             ['F', 'T', 'F', 1-effects_success],
             ['F', 'F', 'T', spont_false_true],
             ['F', 'F', 'F', 1-spont_false_true]], [parent_cpd, action_cpd]
        )
cpds_map[pred_name] = pred_cpd
```
```
cpd = ConditionalProbabilityTable(
        [['T', 'T', 1-spont_true_false],
         ['T', 'F', spont_true_false],
         ['F', 'T', spont_false_true],
         ['F', 'F', 1-spont_false_true]], [parent_cpd]
    )
cpds_map[pred_name] = cpd
```
I believe that the above error stack refers to a CPD initialised in this last manner.
Do you have any idea why I'm getting this error? I do all the calculations before adding the nodes to the model. Hence, the CPDs and nodes are not altered after being added to the model.
I noticed, in the error stack, that the probabilites for the _ConditionalProbabilityTable_ seem to be of type _string_, but I initialised them as _floats_ (e.g. `['T', 'T', 1-spont_true_false]`).

Thank you in advance!

**Comment by jmschrei** [comment]
I'm not sure exactly what the issue is from the code you sent. Is it possible for you to create a minimal example that reproduces the issue? That would be easier for me to find an error in.

**Comment by TomasRibeiro96** [comment]
Hey, while I was trying to build a minimal code I ended up realising where the error was coming from and was able to solve it. The error was from my part.
Thank you for your response.

**Comment by jmschrei** [comment]
Ah, gotcha. Thanks for letting me know.
