### ISSUE TITLE
IndependentComponentsDistribution does not fit DiscreteDistribution components

### ISSUE THREAD

**Issue by shay-zakov** [jmschrei/pomegranate#774]
Hello,

Trying to fit an IndependentComponentsDistribution object on two distributions, one is normal and the other is discrete, only the normal component is fitted. Moreover, after running such fitting, trying to fit the discrete component "externally" (i.e. directly fit the same object used in the construction of the multivariate distribution) produces the error "TypeError: object of type 'NoneType' has no len()". 

The following code generates this behavior:
```python
import pomegranate
import numpy as np

np.random.seed(0)
x = np.column_stack([np.random.randint(5, size=20), np.random.normal(size=20)])

normal_dist = pomegranate.distributions.NormalDistribution(0, 1)
discrete_dist = pomegranate.distributions.DiscreteDistribution(
    dict(zip(range(5), range(5))))
multivariate_dist = pomegranate.distributions.IndependentComponentsDistribution(
    [discrete_dist, normal_dist])
print('\nUnfitted multivariate distribution:'
      '\n-----------------------------------\n', multivariate_dist.parameters)
multivariate_dist.fit(x)
print('\nFitted multivariate distribution:'
      '\n--------------------------------\n', multivariate_dist.parameters)

# Trying to fit the discrete distribution at this point results with an error:

# >>> discrete_dist.fit(x[:, 0])
# Traceback (most recent call last):
#   File "<input>", line 2, in <module>
#   File "pomegranate/distributions/DiscreteDistribution.pyx", line 214, in pomegranate.distributions.DiscreteDistribution.DiscreteDistribution.fit
#   File "pomegranate/distributions/DiscreteDistribution.pyx", line 269, in pomegranate.distributions.DiscreteDistribution.DiscreteDistribution.from_summaries
# TypeError: object of type 'NoneType' has no len()

# This does not happen for the normal distribution (running 'normal_dist.fit(x[:, 1])').
# Also, fitting a new identical discrete distribution works fine:

discrete_dist = pomegranate.distributions.DiscreteDistribution(
    dict(zip(range(5), range(5))))
print('\nFitting discrete distribution outside the multivariate distribution:')
print('Unfitted discrete distribution:'
      '\n-------------------------------\n', discrete_dist.parameters)
discrete_dist.fit(x[:, 0])
print('\nFitted discrete distribution:'
      '\n-----------------------------\n', discrete_dist.parameters)
```

**Comment by jmschrei** [comment]
Yes, unfortunately pomegranate does not support this right now. Sorry about that.
