### ISSUE TITLE
[BUG]  Pomegranate 0.13.3 crashes when training the Bayes net 

### ISSUE THREAD

**Issue by 1021808202** [jmschrei/pomegranate#784]
#when I do this,it is right.
X = numpy.random.randint(10, size=(2000, 7))
X[:,3] = X[:,1] + 2
X[:,6] = X[:,1]

X[:,0] = X[:,2] + X[:,5]

X[:,4] = X[:,5]

model = BayesianNetwork.from_samples(X, algorithm='greedy')

#when I change X = numpy.random.randint(10, size=(2000, 7)) as X = numpy.random.randint(20, size=(2000, 7)),it cannot work
X = numpy.random.randint(20, size=(2000, 7))
X[:,3] = X[:,1] + 2
X[:,6] = X[:,1]

X[:,0] = X[:,2] + X[:,5]

X[:,4] = X[:,5]

model = BayesianNetwork.from_samples(X, algorithm='greedy')

**Comment by ekosman** [comment]
Hi @1021808202 
What is the error?
I'm in the same situation, trying to figure out what happened when upgrading promegranate.
I have this error:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/eitan/PycharmProjects/GAStockPrediction/bayes/bn_train_subset.py", line 253, in <module>
    exps_dir=exps_dir)
  File "C:/Users/eitan/PycharmProjects/GAStockPrediction/bayes/bn_train_subset.py", line 163, in mine_subset
    max_parents=3)
  File "C:\Users\eitan\PycharmProjects\GAStockPrediction\bayes\network\BayesianNetwork.py", line 83, in from_samples
    constraint_graph, pseudocount, state_names, name, reduce_dataset, n_jobs)
  File "pomegranate\BayesianNetwork.pyx", line 1078, in pomegranate.BayesianNetwork.BayesianNetwork.from_samples
TypeError: unsupported operand type(s) for /: 'str' and 'str'

```

**Comment by jmschrei** [comment]
I should add in a warning about this but the issue is that you're trying to build a model that is too big. Remember that the number in a Bayesian network is equal to the sum of the number of values that a variable can take times the number of parent combinations. In your example that means that you'll have 10 ** n_parents parameters in the first example and  20 ** n_parents parameters for each variable. Even when you use the greedy algorithm, the final node that gets added needs to search through all potential parent combos for a total model size of 20 ** 7.
