### ISSUE TITLE
HMM with GaussianKernelDensity do not work?

### ISSUE THREAD

**Issue by mranahmd** [jmschrei/pomegranate#798]
**Description**
-----------------
I am using **pomegranate 0.13.0**.
Trying to use an HMM with GaussianKernelDensity for state-observation distributions. 

Encounter the following issues:
- model.fit() throws the following exception
```
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
```
-  training shows improvements but model checkpoints are same

I think this issue was already introduced in #568 

To Reproduce
-----------------
Sample code:
```
from pomegranate import *
from pomegranate.callbacks import ModelCheckpoint

inits = numpy.random.normal(0, 0.9, size=(100, 2))
dists = [GaussianKernelDensity(inits[:,0],bandwidth=0.1), GaussianKernelDensity(inits[:,1],bandwidth=0.1)]
trans_mat = numpy.array([[0.2, 0.8], [0.7, 0.2]])
starts = numpy.array([1.0, 0.0])
ends = numpy.array([0.0, 0.1])
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends, name='G-KDE_HMM')

obs = numpy.random.normal(0, 1.0, size=(1000, 2))
model.fit(sequences=obs, callbacks=[ModelCheckpoint()], verbose=True)
```

Output from sample code:
```
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
[1] Improvement: 252.57286443082523     Time (s): 0.00609
[1] Saving checkpoint to G-KDE_HMM.1.json
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
[2] Improvement: 0.0    Time (s): 0.005883
[2] Saving checkpoint to G-KDE_HMM.2.json
Total Training Improvement: 252.57286443082523
Total Training Time (s): 0.0238
```

**Comment by jmschrei** [comment]
Yes, unfortunately I added in kernel densities early on but the current methods do not really support them. Sorry about that. You can try implementing a custom distribution that is a kernel density and using that instead.
