### ISSUE TITLE
Networkx >= 2.4 is required for Python 3.9

### ISSUE THREAD

**Issue by tskir** [jmschrei/pomegranate#909]
As reported by one of our users (see: https://github.com/etal/cnvkit/issues/606), the `fractions` module is deprecated in Python 3.9, and because of that, `networkx` versions below 2.4 also stop working.

`pomegranate`'s current dependency specification is `networkx >= 2.0`, which might cause this situation when using Python 3.9:

```
$ python3 -V
Python 3.9.0+

$ python3 -m pip install --quiet --upgrade pomegranate

$ python3 -m pip list | grep -P '(networkx|pomegranate)'
networkx      2.3       
pomegranate   0.14.4

$ python3 -c 'import pomegranate'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/pomegranate/__init__.py", line 12, in <module>
    from .parallel import *
  File "pomegranate/parallel.pyx", line 7, in init pomegranate.parallel
  File "pomegranate/hmm.pyx", line 12, in init pomegranate.hmm
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/home/ktsukanov/repositories/cnvkit/env/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
```

Updating the dependency specification to `networkx >= 2.4` would resolve this problem.

**Comment by jmschrei** [comment]
Requirement updated
