### ISSUE TITLE
[BUG] Upgrade to networkx-2.6.2 (from 2.5.1) breaks two tests: test_exact_dp_structure_learning_exclude_edges and test_constrained_slap_structure_learning_exclude_edges

### ISSUE THREAD

**Issue by trofi** [jmschrei/pomegranate#939]
On NixOS `pomegratate` python packages started failing it's own tests after networkx dependency upgrade from `2.5.1` to `2.6.2`

```
======================================================================
FAIL: tests.test_bayesian_network.test_exact_dp_structure_learning_exclude_edges
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ajpkan6b395jm5p2m1fvljabz66lq0m2-python3.9-nose-1.3.7/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/pomegranate/tests/test_bayesian_network.py", line 1130, in test_exact_dp_structure_learning_exclude_edges
    assert_equal(model.structure[-2], (1,))
AssertionError: Tuples differ: (0,) != (1,)

First differing element 0:
0
1

- (0,)
?  ^

+ (1,)
?  ^


======================================================================
FAIL: tests.test_bayesian_network.test_constrained_slap_structure_learning_exclude_edges
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ajpkan6b395jm5p2m1fvljabz66lq0m2-python3.9-nose-1.3.7/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/pomegranate/tests/test_bayesian_network.py", line 1293, in test_constrained_slap_structure_learning_exclude_edges
    assert_equal(model2.structure[-1], (d-2,))
AssertionError: Tuples differ: (1,) != (2,)

First differing element 0:
1
2

- (1,)
?  ^

+ (2,)
?  ^


----------------------------------------------------------------------
Ran 595 tests in 7.679s

FAILED (failures=2)
Test failed: <unittest.runner.TextTestResult run=595 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=595 errors=0 failures=2>
```

I bisected it down to seemingly benign `networkx` https://github.com/networkx/networkx/commit/15b74c552da64053e5a5003d8c2b7ce0f1997fe9 change:

```diff
Subject: [PATCH] Use bidirection_dijkstra as default in weighted shortest_path
 (#4356)

--- a/networkx/algorithms/shortest_paths/generic.py
+++ b/networkx/algorithms/shortest_paths/generic.py
@@ -159,7 +159,7 @@ def shortest_path(G, source=None, target=None, weight=None, method="dijkstra"):
             if method == "unweighted":
                 paths = nx.bidirectional_shortest_path(G, source, target)
             elif method == "dijkstra":
-                paths = nx.dijkstra_path(G, source, target, weight)
+                _, paths = nx.bidirectional_dijkstra(G, source, target, weight)
             else:  # method == 'bellman-ford':
                 paths = nx.bellman_ford_path(G, source, target, weight)
     return paths
```

Attached example of full build log with tests.
[python3.9-pomegranate-0.13.5-build.log.txt](https://github.com/jmschrei/pomegranate/files/7126559/python3.9-pomegranate-0.13.5-build.log.txt)

**Comment by jmschrei** [comment]
These two tests are ambiguous in that there were multiple optimal Bayesian networks. The previous version of networkx found one of them, and I think due to ordering of ties the current version has found another. I've commented the failing lines out because they weren't required for testing the core functionality.
