### ISSUE TITLE
pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal

### ISSUE THREAD

**Issue by karlasandoval13** [jmschrei/pomegranate#941]
I am trying to build a BN and everything is working up to network.bake().

After that I run the following:
```
prediction = network.predict_proba( observations )
beliefs = map( str, prediction )
probabilities = ("\n&".join( "{}\t\t{}".format( state.name, belief ) for state, belief in zip( network.states, beliefs ) ))
```

And I get the following error:

```
Traceback (most recent call last):
  File "c:\Users\sandoval\Nodes_edges.py", line 167, in <module>
    prediction = network.predict_proba( observations )
  File "pomegranate\BayesianNetwork.pyx", line 595, in pomegranate.BayesianNetwork.BayesianNetwork.predict_proba
  File "pomegranate\FactorGraph.pyx", line 348, in pomegranate.FactorGraph.FactorGraph.predict_proba
  File "pomegranate\distributions\JointProbabilityTable.pyx", line 158, in pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal
ValueError: None is not in list
```

I have tried uninstalling Numpy and installing version 1.20. Also I tried uninstalling pomegranate and installing version 0.11.2 and it is still not working. When doing this the lines where the error occurs change, but the error is still the same. My Python version is 3.9.6

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
