### ISSUE TITLE
Use the fit() show KeyError: 1

### ISSUE THREAD

**Issue by chuangyu-robotics** [jmschrei/pomegranate#951]
hello!
Recently I try the code to fit a bayes network, it shows as below. Code is following. Could you help to tell the reason?

Many thanks.

(tf2) PS D:\1_UoM\1_trust_gui\Code_V3_with_BNN_Real_data> python .\bnn_fit.py
C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File ".\bnn_fit.py", line 41, in <module>
    bnn.fit(samples)
  File "pomegranate\BayesianNetwork.pyx", line 703, in pomegranate.BayesianNetwork.BayesianNetwork.fit
  File "pomegranate\BayesianNetwork.pyx", line 705, in pomegranate.BayesianNetwork.BayesianNetwork.fit
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\_parallel_backends.py", line 209, in apply_async    result = ImmediateResult(func)
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\Administrator\.conda\envs\tf2\lib\site-packages\joblib\parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "pomegranate\BayesianNetwork.pyx", line 1154, in pomegranate.BayesianNetwork.BayesianNetwork.summarize
KeyError: 1
-------code------
# The guests initial door selection is completely random
guest = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})

# The door the prize is behind is also completely random
prize = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})

    # Monty is dependent on both the guest and the prize. 
monty = ConditionalProbabilityTable(
        [[ 'A', 'A', 'A', 0.0 ],
         [ 'A', 'A', 'B', 0.5 ],
         [ 'A', 'A', 'C', 0.5 ],
         [ 'A', 'B', 'A', 0.0 ],
         [ 'A', 'B', 'B', 0.0 ],
         [ 'A', 'B', 'C', 1.0 ],
         [ 'A', 'C', 'A', 0.0 ],
         [ 'A', 'C', 'B', 1.0 ],
         [ 'A', 'C', 'C', 0.0 ],
         [ 'B', 'A', 'A', 0.0 ],
         [ 'B', 'A', 'B', 0.0 ],
         [ 'B', 'A', 'C', 1.0 ],
         [ 'B', 'B', 'A', 0.5 ],
         [ 'B', 'B', 'B', 0.0 ],
         [ 'B', 'B', 'C', 0.5 ],
         [ 'B', 'C', 'A', 1.0 ],
         [ 'B', 'C', 'B', 0.0 ],
         [ 'B', 'C', 'C', 0.0 ],
         [ 'C', 'A', 'A', 0.0 ],
         [ 'C', 'A', 'B', 1.0 ],
         [ 'C', 'A', 'C', 0.0 ],
         [ 'C', 'B', 'A', 1.0 ],
         [ 'C', 'B', 'B', 0.0 ],
         [ 'C', 'B', 'C', 0.0 ],
         [ 'C', 'C', 'A', 0.5 ],
         [ 'C', 'C', 'B', 0.5 ],
         [ 'C', 'C', 'C', 0.0 ]], [guest, prize])  

# State objects hold both the distribution, and a high level name.
s1 = State(guest, name="guest")
s2 = State(prize, name="prize")
s3 = State(monty, name="monty")

# Create the Bayesian network object with a useful name
model = BayesianNetwork("Monty Hall Problem")

# Add the three states to the network 
model.add_states(s1, s2, s3)

# Add edges which represent conditional dependencies, where the second node is 
# conditionally dependent on the first node (Monty is dependent on both guest and prize)
model.add_edge(s1, s3)
model.add_edge(s2, s3)

model.bake()

samples=np.ones([100,4])
bnn.fit(samples)

-------------
win10 python3.7.3

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
